export const defaultEmployeeProfileConfigData = [
  {
    sectionKey: "personaldetails",
    sectionLabel: "Personal Details",
    fields: [
      {
        key: "employeephoto",
        label: "Employee Photo",
        placeholder: "Enter Employee Photo",
        required: false,
        hint: "Enter the field",
        type: "file",
      },
      {
        key: "firstname",
        label: "First Name",
        placeholder: "Enter First Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "middlename",
        label: "Middle Name",
        placeholder: "Enter Middle Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "lastname",
        label: "Last Name",
        placeholder: "Enter Last Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "preferredname",
        label: "Preferred Name",
        placeholder: "Enter Preferred Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "mobile",
        label: "Mobile",
        placeholder: "Enter Mobile",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "dob",
        label: "Date of Birth",
        placeholder: "Enter DOB",
        required: false,
        hint: "Enter the field",
        type: "date",
      },
      {
        key: "gender",
        label: "Gender",
        placeholder: "Enter Gender",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Male", "Female", "Intersex", "Don't want to Specify"],
      },
      {
        key: "pronouns",
        label: "Pronouns",
        placeholder: "Enter Pronouns",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["He/Him", "She/Her", "They/Them"],
      },
      {
        key: "aboriginalortorresstraitislanderorigin",
        label: "Aboriginal or Torres Strait Islander Origin?",
        placeholder: "Enter Aboriginal or Torres Strait Islander Origin",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "No",
          "Yes, Aboriginal",
          "Yes, Torres Strait Islander",
          "Yes, Both",
        ],
      },
      // {
      //   key: "lgbtq",
      //   label: "Select Type Of LGBTQ",
      //   placeholder: "Enter Type Of LGBTQ",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "select",
      //   options: [
      //     "Lesbian",
      //     "Gay",
      //     "Bisexual",
      //     "Transgender",
      //     "Queer",
      //     "Intersex",
      //     "Asexual",
      //   ],
      //   showIf: {
      //     fieldKey: "gender",
      //     operator: "equals",
      //     value: "LGBTQ",
      //   },
      // },
      {
        key: "countryofbirth",
        label: "Country of Birth",
        placeholder: "Select Country of Birth",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [], // Will be populated from COUNTRIES list in frontend
        isCountrySelect: true,
      },
      {
        key: "countryofcitizenship",
        label: "Country of Citizenship",
        placeholder: "Select Country of Citizenship",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [], // Will be populated from COUNTRIES list in frontend
        isCountrySelect: true,
        isMulti: true,
      },
      {
        key: "languagesspeak",
        label: "Languages Speak",
        placeholder: "Select Languages",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "English",
          "Spanish",
          "French",
          "German",
          "Italian",
          "Portuguese",
          "Russian",
          "Chinese (Mandarin)",
          "Chinese (Cantonese)",
          "Japanese",
          "Korean",
          "Arabic",
          "Hindi",
          "Bengali",
          "Urdu",
          "Turkish",
          "Vietnamese",
          "Thai",
          "Indonesian",
          "Malay",
          "Tagalog",
          "Dutch",
          "Greek",
          "Hebrew",
          "Swedish",
          "Norwegian",
          "Danish",
          "Finnish",
          "Polish",
          "Czech",
          "Hungarian",
          "Romanian",
          "Bulgarian",
          "Croatian",
          "Serbian",
          "Slovak",
          "Slovenian",
          "Other",
        ],
        isMulti: true,
      },
      {
        key: "residencystatus",
        label: "Residency Status",
        placeholder: "Enter Residency Status",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Australian Citizen", "Permanent Resident", "Visa Holder"],
      },
      {
        key: "typeofvisa",
        label: "Type Of Visa",
        placeholder: "Enter Type Of Visa",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Work Visa", "Student Visa", "Working Holiday Visa"],
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },

      {
        key: "visasubcategory",
        label: "Visa Sub Category",
        placeholder: "Enter Visa Sub Category",
        required: false,
        hint: "Enter the field",
        type: "text",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      {
        key: "visastartdate",
        label: "Visa Start Date",
        placeholder: "Enter Visa Start Date",
        required: false,
        hint: "Enter the field",
        type: "date",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      {
        key: "visaenddate",
        label: "Visa End Date",
        placeholder: "Enter Visa End Date",
        required: false,
        hint: "Enter the field",
        type: "date",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      // {
      //   key: "nameofinstitutionstudying",
      //   label: "Name of Institution Studying",
      //   placeholder: "Enter Name of Institution Studying",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "text",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
      // {
      //   key: "coursestartdate",
      //   label: "Course Start Date",
      //   placeholder: "Enter Course Start Date",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "date",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
      // {
      //   key: "courseenddate",
      //   label: "Course End Date",
      //   placeholder: "Enter Course End Date",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "date",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
    ],
    innerSections: [
      {
        sectionKey: "emergencycontact",
        sectionLabel: "Emergency Contact",
        fields: [
          {
            key: "emergency-contact-name",
            label: "Name",
            placeholder: "Enter Name",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
          {
            key: "emergency-contact-relationship",
            label: "Relationship",
            placeholder: "Enter Relationship",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
          {
            key: "emergency-contact-mobile",
            label: "Mobiile",
            placeholder: "Enter Mobile",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
        ],
      },
    ],
  },
  {
    sectionKey: "address",
    sectionLabel: "Address",
    fields: [
      {
        key: "addressFor",
        label: "Address For",
        placeholder: "Address For",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "buildingpropertyname",
        label: "Building / Property name",
        placeholder: "Enter Building / Property name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "flatunitnumber",
        label: "Flat/Unit Number",
        placeholder: "Enter Flat/Unit Number",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "streetnumber",
        label: "Street Number",
        placeholder: "Enter Street Number",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "streetname",
        label: "Street Name",
        placeholder: "Enter Street Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "suburbcity",
        label: "Suburb / City",
        placeholder: "Enter Suburb / City",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "stateterritiory",
        label: "State / Territiory",
        placeholder: "Enter State / Territiory",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "country",
        label: "Country",
        placeholder: "Enter Country",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "zippostalcode",
        label: "Zip / Postal Code",
        placeholder: "Enter Zip / Postal Code",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
    ],
  },
  // documents-----------------------
  {
    sectionKey: "documents",
    sectionLabel: "Documents",
    fields: [],
    innerSections: [
      {
        sectionKey: "identificationdocuments",
        sectionLabel: "Identification Documents",
        requirementMode: "OR", // any 1 required
        fields: [
          {
            key: "driverslicence",
            label: "Drivers Licence",
            placeholder: "Enter Drivers Licence",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
            },
          },
          {
            key: "passport",
            label: "Passport",
            placeholder: "Enter Passport",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
              countryOfIssue: true,
            },
          },
          {
            key: "birthcertificate",
            label: "Birth Certificate",
            placeholder: "Enter Birth Certificate",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
            },
          },
          {
            key: "australiancitizenshipcertificate",
            label: "Australian Citizenship Certificate",
            placeholder: "Enter Australian Citizenship Certificate",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
            },
          },
          {
            key: "medicarecard",
            label: "Medicare Card",
            placeholder: "Enter Medicare Card",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: false,
            },
          },
          {
            key: "proofofagecard",
            label: "Proof of Age Card",
            placeholder: "Enter Proof of Age Card",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: false,
            },
          },
        ],
      },
      {
        sectionKey: "certificates",
        sectionLabel: "Certificates",
        requirementMode: "AND", // all required if the section is marked mandatory
        fields: [
          {
            key: "cpr",
            label: "CPR",
            placeholder: "Enter CPR",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
            },
          },
          {
            key: "firstaid",
            label: "First Aid",
            placeholder: "Enter First Aid",
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
            },
          },
          {
            key: "manualhandling",
            label: "Manual Handling",
            placeholder: "Enter Manual Handling",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
            },
          },
          {
            key: "medicationcompletency",
            label: "Medication Completency",
            placeholder: "Enter Medication Completency",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
            },
          },
        ],
      },
      {
        sectionKey: "checksandclearance",
        sectionLabel: "Checks & Clearances",
        requirementMode: "AND", // all required if section mandatory
        fields: [
          {
            key: "policeclearancecertificate",
            label: "Police Clearance Certificate",
            placeholder: "Enter Police Clearance Certificate",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
            },
          },
          {
            key: "ndisscreensingcheck",
            label: "NDIS Screensing Check",
            placeholder: "Enter NDIS Screensing Check",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: true,
              validityPeriod: "10 Years",
              issuingDate: true,
            },
          },
          {
            key: "covid19vaccinationcertificate",
            label: "COVID 19 Vaccination Certificate",
            placeholder: "Enter COVID 19 Vaccination Certificate",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
            },
          },
        ],
      },
      // {
      //   sectionKey: "uploadadditionaldocument",
      //   sectionLabel: "Upload Additional Document",
      //   requirementMode: "OR", // optional: you could leave this undefined or OR
      //   fields: [
      //     {
      //       key: "document1",
      //       label: "Document 1",
      //       placeholder: "Document 1",
      //       // required: false,
      //       type: "file",
      //       fileMeta: {
      //         expiryDate: false,
      //         // mandatoryStatus: "Not Mandatory",
      //         points: 0,
      //         referenceNumber: false,
      //         issuingDate: false,
      //       },
      //     },
      //     {
      //       key: "document2",
      //       label: "Document 2",
      //       placeholder: "Document 2",
      //       // required: false,
      //       type: "file",
      //       fileMeta: {
      //         expiryDate: false,
      //         // mandatoryStatus: "Not Mandatory",
      //         points: 0,
      //         referenceNumber: false,
      //         issuingDate: false,
      //       },
      //     },
      //     {
      //       key: "document3",
      //       label: "Document 3",
      //       placeholder: "Document 3",
      //       // required: false,
      //       type: "file",
      //       fileMeta: {
      //         expiryDate: false,
      //         // mandatoryStatus: "Not Mandatory",
      //         points: 0,
      //         referenceNumber: false,
      //         issuingDate: false,
      //       },
      //     },
      //   ],
      // },
    ],
  },
];
