export const defaultConfigData = [
  {
    sectionKey: "personaldetails",
    sectionLabel: "Personal Details",
    employeeAccess: "edit",
    fields: [
      {
        key: "employeephoto",
        label: "Employee Photo",
        placeholder: "Enter Employee Photo",
        required: false,
        hint: "Enter the field",
        type: "file",
      },
      {
        key: "firstname",
        label: "First Name",
        placeholder: "Enter First Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "middlename",
        label: "Middle Name",
        placeholder: "Enter Middle Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "lastname",
        label: "Last Name",
        placeholder: "Enter Last Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "preferredname",
        label: "Preferred Name",
        placeholder: "Enter Preferred Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "mobile",
        label: "Mobile",
        placeholder: "Enter Mobile",
        required: true,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "dob",
        label: "Date of Birth",
        placeholder: "Enter DOB",
        required: false,
        hint: "Enter the field",
        type: "date",
      },
      {
        key: "gender",
        label: "Gender",
        placeholder: "Enter Gender",
        required: true,
        hint: "Enter the field",
        type: "select",
        options: ["Male", "Female", "Intersex", "Don't want to Specify"],
      },
      {
        key: "pronouns",
        label: "Pronouns",
        placeholder: "Enter Pronouns",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["He/Him", "She/Her", "They/Them"],
      },
      {
        key: "aboriginalortorresstraitislanderorigin",
        label: "Aboriginal or Torres Strait Islander Origin?",
        placeholder: "Enter Aboriginal or Torres Strait Islander Origin",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "No",
          "Yes, Aboriginal",
          "Yes, Torres Strait Islander",
          "Yes, Both",
        ],
      },
      // {
      //   key: "lgbtq",
      //   label: "Select Type Of LGBTQ",
      //   placeholder: "Enter Type Of LGBTQ",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "select",
      //   options: [
      //     "Lesbian",
      //     "Gay",
      //     "Bisexual",
      //     "Transgender",
      //     "Queer",
      //     "Intersex",
      //     "Asexual",
      //   ],
      //   showIf: {
      //     fieldKey: "gender",
      //     operator: "equals",
      //     value: "LGBTQ",
      //   },
      // },
      {
        key: "countryofbirth",
        label: "Country of Birth",
        placeholder: "Select Country of Birth",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [], // Will be populated from COUNTRIES list in frontend
        isCountrySelect: true,
      },
      {
        key: "countryofcitizenship",
        label: "Country of Citizenship",
        placeholder: "Select Country of Citizenship",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [], // Will be populated from COUNTRIES list in frontend
        isCountrySelect: true,
        isMulti: true,
      },
      {
        key: "languagesspeak",
        label: "Languages Speak",
        placeholder: "Select Languages",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "English",
          "Spanish",
          "French",
          "German",
          "Italian",
          "Portuguese",
          "Russian",
          "Chinese (Mandarin)",
          "Chinese (Cantonese)",
          "Japanese",
          "Korean",
          "Arabic",
          "Hindi",
          "Bengali",
          "Urdu",
          "Turkish",
          "Vietnamese",
          "Thai",
          "Indonesian",
          "Malay",
          "Tagalog",
          "Dutch",
          "Greek",
          "Hebrew",
          "Swedish",
          "Norwegian",
          "Danish",
          "Finnish",
          "Polish",
          "Czech",
          "Hungarian",
          "Romanian",
          "Bulgarian",
          "Croatian",
          "Serbian",
          "Slovak",
          "Slovenian",
          "Other",
        ],
        isMulti: true,
      },
      {
        key: "residencystatus",
        label: "Residency Status",
        placeholder: "Enter Residency Status",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Australian Citizen", "Permanent Resident", "Visa Holder"],
      },
      {
        key: "typeofvisa",
        label: "Type Of Visa",
        placeholder: "Enter Type Of Visa",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Work Visa", "Student Visa", "Working Holiday Visa"],
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },

      {
        key: "visasubcategory",
        label: "Visa Sub Category",
        placeholder: "Enter Visa Sub Category",
        required: false,
        hint: "Enter the field",
        type: "text",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      {
        key: "visastartdate",
        label: "Visa Start Date",
        placeholder: "Enter Visa Start Date",
        required: false,
        hint: "Enter the field",
        type: "date",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      {
        key: "visaenddate",
        label: "Visa End Date",
        placeholder: "Enter Visa End Date",
        required: false,
        hint: "Enter the field",
        type: "date",
        showIf: {
          fieldKey: "residencystatus",
          operator: "equals",
          value: "Visa Holder",
        },
      },
      // {
      //   key: "nameofinstitutionstudying",
      //   label: "Name of Institution Studying",
      //   placeholder: "Enter Name of Institution Studying",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "text",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
      // {
      //   key: "coursestartdate",
      //   label: "Course Start Date",
      //   placeholder: "Enter Course Start Date",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "date",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
      // {
      //   key: "courseenddate",
      //   label: "Course End Date",
      //   placeholder: "Enter Course End Date",
      //   required: false,
      //   hint: "Enter the field",
      //   type: "date",
      //   showIf: {
      //     fieldKey: "typeofvisa",
      //     operator: "equals",
      //     value: "Student Visa",
      //   },
      // },
    ],
    innerSections: [
      {
        sectionKey: "emergencycontact",
        sectionLabel: "Emergency Contact",
        fields: [
          {
            key: "emergency-contact-name",
            label: "Name",
            placeholder: "Enter Name",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
          {
            key: "emergency-contact-relationship",
            label: "Relationship",
            placeholder: "Enter Relationship",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
          {
            key: "emergency-contact-mobile",
            label: "Mobiile",
            placeholder: "Enter Mobile",
            required: false,
            hint: "Enter the field",
            type: "text",
          },
        ],
      },
    ],
  },
  {
    sectionKey: "address",
    sectionLabel: "Address",
    employeeAccess: "edit",
    fields: [
      {
        key: "addressFor",
        label: "Address For",
        placeholder: "Address For",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "buildingpropertyname",
        label: "Building / Property name",
        placeholder: "Enter Building / Property name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "flatunitnumber",
        label: "Flat/Unit Number",
        placeholder: "Enter Flat/Unit Number",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "streetnumber",
        label: "Street Number",
        placeholder: "Enter Street Number",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "streetname",
        label: "Street Name",
        placeholder: "Enter Street Name",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "suburbcity",
        label: "Suburb / City",
        placeholder: "Enter Suburb / City",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "stateterritiory",
        label: "State / Territiory",
        placeholder: "Enter State / Territiory",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "country",
        label: "Country",
        placeholder: "Enter Country",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
      {
        key: "zippostalcode",
        label: "Zip / Postal Code",
        placeholder: "Enter Zip / Postal Code",
        required: false,
        hint: "Enter the field",
        type: "text",
      },
    ],
  },
  {
    sectionKey: "employeedetails",
    sectionLabel: "Employment Details",
    isAdditional: true,
    employeeAccess: "hidden",
    fields: [
      {
        key: "employmentstatus",
        label: "Employment Status",
        placeholder: "Enter Employment Status",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "Reference Check Started",
          "Reference Check Satisfactory",
          "Reference Check Unsatisfactory",
          "Offer Letter Issued",
          "Offer Accepted",
          "Offer Rejected",
          "Onboard",
          "No Show",
          "Resigned",
          "Terminated",
        ],
        isAdditional: true,
      },
      {
        key: "employmentstartdate",
        label: "Employment Start Date",
        placeholder: "Enter Employment Start Date",
        required: false,
        hint: "Enter the field",
        type: "date",
        isAdditional: true,
      },
      {
        key: "worktype",
        label: "Work Type",
        placeholder: "Select Work Type",
        required: false,
        hint: "Select the work type",
        type: "select",
        options: ["Office Work", "Shift Work"],
        isAdditional: true,
      },
      {
        key: "employeetype",
        label: "Employment Type",
        placeholder: "Enter Employee Type",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: [
          "Permanent Full Time",
          "Permanent Part Time",
          "Fixed Term Contract",
          "Casual",
          "Labour Hire",
        ],
        isAdditional: true,
      },
      {
        key: "parttimeterm",
        label: "Part Time Term",
        placeholder: "Part Time Term",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["4 Days a week", "Fort Night", "Month"],
        showIf: {
          fieldKey: "employeetype",
          operator: "equals",
          value: "Part Time",
        },
        isAdditional: true,
      },
      {
        key: "contractualparttimehours",
        label: "Contractual Part Time Hours",
        placeholder: "Part Time Term",
        required: false,
        hint: "Enter the field",
        type: "text",
        showIf: {
          fieldKey: "employeetype",
          operator: "equals",
          value: "Part Time",
        },
        isAdditional: true,
      },
      {
        key: "fixedterm",
        label: "Fixed Term",
        placeholder: "Fixed Term",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["1 Month", "2Months", "6 Months", "1 Year", "2 Year"],
        showIf: {
          fieldKey: "employeetype",
          operator: "equals",
          value: "Fixed Term Contract",
        },
        isAdditional: true,
      },
      {
        key: "reportingTo",
        label: "Reporting To",
        placeholder: "Select Reporting To",
        required: false,
        hint: "Select the reporting employee",
        type: "reference",
        referenceModel: "Employee", // 👈 reference to Employee collection
        isAdditional: true,
      },
      {
        key: "functionalreporting",
        label: "Functional Reporting",
        placeholder: "Select Functional Reporting",
        required: false,
        hint: "Select the reporting employee",
        type: "reference",
        referenceModel: "Employee", // 👈 reference to Employee collection
        isAdditional: true,
      },
    ],
  },
  // {
  //   sectionKey: "payrolldetails",
  //   sectionLabel: "Payroll Details",
  //   employeeAccess: "hidden",
  //   isAdditional: true,
  //   fields: [
  //     {
  //       key: "fulltimeparttimebaserate",
  //       label: "Full Time/Part Time Base Rate",
  //       placeholder: "Enter Full Time/Part Time Base Rate",
  //       required: false,
  //       hint: "Enter the field",
  //       type: "text",
  //       isAdditional: true,
  //     },
  //     {
  //       key: "paymentintervalweeklyfortnightlymonthly",
  //       label: "Payment Interval",
  //       placeholder: "Enter Payment Interval",
  //       required: false,
  //       hint: "Enter the field",
  //       type: "select",
  //       options: ["Weekly", "Fortnightly", "Monthly"],
  //       isAdditional: true,
  //     },
  //   ],
  // },
  {
    sectionKey: "payrolldetailsForEmployee",
    sectionLabel: "Payroll Details",
    employeeAccess: "edit",
    isAdditional: true,
    fields: [
      {
        key: "taxfilenumber",
        label: "Tax File Number",
        placeholder: "Enter Tax File Number",
        required: false,
        hint: "Enter the field",
        type: "text",
        isAdditional: true,
      },
      {
        key: "claimtaxfreethresholdyesno",
        label: "Claim Tax Free Threshold",
        placeholder: "Select Claim Tax Free Threshold",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Yes", "No"],
        isAdditional: true,
      },
      {
        key: "anyloan",
        label: "Do you have any Loan",
        placeholder:
          "Enter Do you have a Higher Education Loan Program (HELP), VET Student Loan (VSL), Financial Supplement (FS) Student Start-up Loan (SSL) or Trade Support Loan (TSL) debt? \u2013 Yes/No",
        required: false,
        hint: "Enter the field",
        type: "select",
        options: ["Yes", "No"],
        isAdditional: true,
      },
    ],
    innerSections: [
      {
        sectionKey: "bankaccountdetails",
        sectionLabel: "Bank Account Details",
        fields: [
          {
            key: "bankname",
            label: "Bank Name",
            placeholder: "Enter Bank Name",
            required: false,
            type: "text",
            isAdditional: true,
          },
          {
            key: "bsb",
            label: "BSB",
            placeholder: "Enter BSB",
            required: false,
            type: "text",
            isAdditional: true,
          },
          {
            key: "accountnumber",
            label: "Account Number",
            placeholder: "Enter Account Number",
            required: false,
            type: "text",
            isAdditional: true,
          },
        ],
      },
      {
        sectionKey: "awardsandlevels",
        sectionLabel: "Payrolls Details Entry",
        employeeAccess: "view",
        fields: [
          {
            key: "award",
            label: "Award",
            placeholder: "Select Award",
            required: false,
            hint: "Select the award",
            type: "reference",
            referenceModel: "Award",
            isAdditional: true,
          },
          {
            key: "awardtype",
            label: "Award EmployeeType",
            placeholder: "Select Award Employee Type",
            required: false,
            hint: "Select the award employee type",
            type: "reference",
            referenceModel: "AwardEmployeeType",
            isAdditional: true,
          },
          {
            key: "awardlevel",
            label: "Award Level",
            placeholder: "Select Award Level",
            required: false,
            hint: "Select the award level",
            type: "select",
            options: [], // Will be populated dynamically from hourly rate management
            isAdditional: true,
          },
          {
            key: "hourlyrate",
            label: "Hourly Rate",
            placeholder: "Enter Hourly Rate",
            required: false,
            hint: "Enter the hourly rate",
            type: "number",
            isAdditional: true,
          },
          {
            key: "supercontribution",
            label: "Super Contribution %",
            placeholder: "Enter Super Contribution %",
            required: false,
            hint: "Enter the super contribution percentage",
            type: "number",
            defaultValue: 11,
            isAdditional: true,
          },
          {
            key: "probationperiod",
            label: "Probation Period",
            placeholder: "Select Probation Period",
            required: false,
            hint: "Select the probation period",
            type: "select",
            defaultValue: "3 Months",
            options: [
              "1 Month",
              "2 Months",
              "3 Months",
              "4 Months",
              "5 Months",
              "6 Months",
              "7 Months",
              "8 Months",
              "9 Months",
              "10 Months",
              "11 Months",
              "12 Months",
            ],
            isAdditional: true,
          },
          {
            key: "casualrate",
            label: "Casual Rate %",
            placeholder: "Enter Casual Rate %",
            required: false,
            hint: "Enter the casual rate percentage",
            type: "number",
            defaultValue: 25,
            isAdditional: true,
          },
          {
            key: "annualleave",
            label: "Annual Leave %",
            placeholder: "Enter Annual Leave %",
            required: false,
            hint: "Enter the annual leave percentage",
            type: "number",
            defaultValue: 10.5,
            isAdditional: true,
          },
          {
            key: "salarypackage",
            label: "Salary Package",
            placeholder: "Select Salary Package",
            required: false,
            hint: "Select if salary package is applicable",
            type: "select",
            options: ["Yes", "No"],
            isAdditional: true,
          },
          {
            key: "salarypackagemaximumamount",
            label: "Salary Package Maximum Amount",
            placeholder: "Enter Salary Package Maximum Amount",
            required: false,
            hint: "Enter the maximum amount for salary package",
            type: "number",
            showIf: {
              fieldKey: "salarypackage",
              operator: "equals",
              value: "yes",
            },
            isAdditional: true,
          },
        ],
      },
    ],
  },
  // documents-----------------------
  {
    sectionKey: "documents",
    sectionLabel: "Documents",
    employeeAccess: "edit",
    innerSections: [
      {
        sectionKey: "identificationdocuments",
        sectionLabel: "Identification Documents",
        requirementMode: "OR", // any 1 required
        fields: [
          {
            key: "driverslicence",
            label: "Drivers Licence",
            placeholder: "Enter Drivers Licence",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "5 Years",
              expiryIsDisabled: true, // expiry auto-calculated + locked
            },
          },
          {
            key: "passport",
            label: "Passport",
            placeholder: "Enter Passport",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "10 Years",
              expiryIsDisabled: true,
              countryOfIssue: true,
            },
          },
          {
            key: "birthcertificate",
            label: "Birth Certificate",
            placeholder: "Enter Birth Certificate",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
              // allow manual expiry editing (no issuing date)
              validityPeriod: undefined,
              expiryIsDisabled: false,
            },
          },
          {
            key: "australiancitizenshipcertificate",
            label: "Australian Citizenship Certificate",
            placeholder: "Enter Australian Citizenship Certificate",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
              // validityPeriod: "10 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "medicarecard",
            label: "Medicare Card",
            placeholder: "Enter Medicare Card",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "5 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "proofofagecard",
            label: "Proof of Age Card",
            placeholder: "Enter Proof of Age Card",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "10 Years",
              expiryIsDisabled: true,
            },
          },
        ],
      },
      {
        sectionKey: "certificates",
        sectionLabel: "Certificates",
        requirementMode: "AND", // all required if the section is marked mandatory
        fields: [
          {
            key: "cpr",
            label: "CPR",
            placeholder: "Enter CPR",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "1 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "firstaid",
            label: "First Aid",
            placeholder: "Enter First Aid",
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "3 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "manualhandling",
            label: "Manual Handling",
            placeholder: "Enter Manual Handling",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
              validityPeriod: "1 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "medicationcompletency",
            label: "Medication Completency",
            placeholder: "Enter Medication Completency",
            type: "file",
            fileMeta: {
              expiryDate: false,
              issuingDate: true,
              validityPeriod: "1 Years",
              expiryIsDisabled: true,
            },
          },
        ],
      },
      {
        sectionKey: "checksandclearance",
        sectionLabel: "Checks & Clearances",
        requirementMode: "AND", // all required if section mandatory
        fields: [
          {
            key: "policeclearancecertificate",
            label: "Police Clearance Certificate",
            placeholder: "Enter Police Clearance Certificate",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: true,
              issuingDate: true,
              validityPeriod: "3 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "ndisscreensingcheck",
            label: "NDIS Screensing Check",
            placeholder: "Enter NDIS Screensing Check",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: true,
              // mandatoryStatus: "Mandatory Now",
              issuingDate: true,
              validityPeriod: "5 Years",
              expiryIsDisabled: true,
            },
          },
          {
            key: "covid19vaccinationcertificate",
            label: "COVID 19 Vaccination Certificate",
            placeholder: "Enter COVID 19 Vaccination Certificate",
            // required: true,
            type: "file",
            fileMeta: {
              expiryDate: false,
              // mandatoryStatus: "Not Mandatory",
              issuingDate: true,
              // validityPeriod: "10 Years",
              expiryIsDisabled: true,
            },
          },
        ],
      },
    ],
  },
];

// {
//   sectionKey: "uploadadditionaldocument",
//   sectionLabel: "Upload Additional Document",
//   requirementMode: "AND", // optional: you could leave this undefined or OR
//   fields: [
//     {
//       key: "other_document",
//       label: "Other Document",
//       placeholder: "Add Additional Document If Any",
//       // required: false,
//       type: "file",
//       fileMeta: {
//         expiryDate: false,
//         // mandatoryStatus: "Not Mandatory",
//         points: 0,
//         referenceNumber: false,
//         issuingDate: false,
//       },
//     },
//   ],
// },

// {
//   sectionKey: "main",
//   sectionLabel: "Main",
//   fields: [
//     // {
//     //   key: "employeename",
//     //   label: "Employee Name",
//     //   placeholder: "Enter Employee Name",
//     //   required: false,
//     //   hint: "Enter the field",
//     //   type: "text",
//     // },
//     // {
//     //   key: "designation",
//     //   label: "Designation",
//     //   placeholder: "Enter Designation",
//     //   required: false,
//     //   hint: "Enter the field",
//     //   type: "text",
//     // },
//     {
//       key: "reportingto",
//       label: "Reporting To",
//       placeholder: "Enter Reporting To",
//       required: false,
//       hint: "Enter the field",
//       type: "text",
//     },

//     // {
//     //   key: "department",
//     //   label: "Department",
//     //   placeholder: "Enter Department",
//     //   required: false,
//     //   hint: "Enter the field",
//     //   type: "text",
//     // },

//   ],
// },
